<?php
/* THIS IS THE FUNCTION CALLED FROM THE ROUTES.  WE COULD HAVE MORE THAN ONE FUNCTION HERE AND WE CAN DO OTHER OPERATON LIKE ACCESS A DATABASE, READ A FILE, WRITE TO A DATABASE OR FILE.

THE FUNCTION BELOW RETURNS AND ASSOCIATIVE ARRAY THAT IS USED TO SUPPLY INDIVIDUAL CONTENT (HEADING 1 TEXT, NAVIGATION, TITLE, MAIN CONTENT) TO EACH PAGE.  IN THIS EXAMPLE I JUST HAVE A FEW THINGS BUT YOU COULD EASILY ADD MORE.

*/
function general($page, $heading, $nav="user"){
	return array(
		"title"=>$heading,
		"heading"=>$heading, 
		"nav"=>$nav,
		"main"=>file_get_contents('views/'.$page.'.html'));
}
?>